#
# App: Customer Registration
# Package: docker
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 1
# Author: ChatGPT Codex
# Date: 2025-02-14T00:00:00Z
# Exports: docker-compose
# Description: Local container orchestration for Customer Registration dependencies.
#
version: "3.9"

services:
  postgresql-db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    container_name: customer-registration-postgres
    restart: unless-stopped
    profiles: [postgresql]
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.postgresql

volumes:
  pgdata:
