# App: Customer Registration
# Package: project-root
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 1
# Author: Bobwares (bobwares@outlook.com)
# Date: 2025-10-26T00:40:26Z
# Exports: Docker Compose definition
# Description: Provides a PostgreSQL service for local development of the Customer Registration API.

version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-shopping
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME:-customer}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-customer}"
      POSTGRES_DB: "${DATABASE_NAME:-customer_registration}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-customer} -d ${DATABASE_NAME:-customer_registration}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations:ro
    env_file:
      - .env

volumes:
  pgdata:
