# App: Customer Registration
# Package: infrastructure
# File: docker-compose.yml
# Version: 0.1.0
# Turns: 1
# Author: AI
# Date: 2025-10-28T15:32:47Z
# Exports: PostgreSQL container, Spring Boot service container
# Description: Defines local development containers for PostgreSQL and the Customer Registration Spring Boot service.
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "${APP_PORT:-8080}:8080"

volumes:
  pgdata:
