# **
# * App: Customer Registration
# * Package: infrastructure
# * File: docker-compose.yml
# * Version: 0.1.0
# * Turns: 1
# * Author: AI Agent
# * Date: 2025-10-29T22:24:49Z
# * Exports: postgres-service
# * Description: Local development Docker Compose stack providing PostgreSQL for the service.
# **
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-customer-registration
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env

volumes:
  pgdata:
