# App: Customer Registration
# Package: src.main.resources
# File: application.yml
# Version: 0.1.0
# Turns: 1
# Author: AI Coding Agent
# Date: 2025-10-29T16:56:41Z
# Exports: application.yml
# Description: Configures datasource, Liquibase, Springdoc, management, and app defaults.

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  main:
    allow-bean-definition-overriding: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: ${APP_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  observations:
    key-values:
      application: ${APP_NAME}
app:
  name: ${APP_NAME}
  default-tax-rate: ${APP_DEFAULT_TAX_RATE}
  default-shipping-cost: ${APP_DEFAULT_SHIPPING_COST}
  supported-currencies: ${APP_SUPPORTED_CURRENCIES}
