# App: Customer Registration
# Package: resources
# File: application.yml
# Version: 0.1.0
# Turns: 1
# Author: AI
# Date: 2025-10-28T15:32:47Z
# Exports: Spring configuration
# Description: Configures database, Liquibase, JPA, and documentation endpoints for the Customer Registration service.
spring:
  application:
    name: customer-registration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:customer_registration}
    username: ${DB_USERNAME:customer}
    password: ${DB_PASSWORD:customer}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:}
    default-schema: ${DATABASE_SCHEMA:public}
    drop-first: false
    parameters:
      appName: customer-registration

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
