# /**
# * App: Customer Registration
# * Package: com.bobwares.customer.registration
# * File: application.yml
# * Version: 0.1.0
# * Turns: 1
# * Author: Codex Agent
# * Date: 2025-09-12T00:01:14Z
# * Exports: n/a
# * Description: Spring Boot application configuration.
# */
spring:
  application:
    name: customer-registration
