# App: Customer Registration
# Package: application
# File: application.yml
# Version: 0.1.0
# Turns: 1
# Author: Codex Agent
# Date: 2025-09-14T03:38:27Z
# Exports: none
# Description: Spring Boot configuration with PostgreSQL, Liquibase, and Springdoc.

spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    contexts: ${LIQUIBASE_CONTEXTS:}
    default-schema: ${DB_SCHEMA:public}
    drop-first: false
    parameters:
      appName: ${APP_NAME}

server:
  port: ${APP_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

