# /**
# * App: Customer Registration
# * Package: com.bobwares.customer.registration
# * File: application.yml
# * Version: 0.1.0
# * Turns: 1
# * Author: codex
# * Date: 2025-09-13T02:16:18Z
# * Exports: application configuration
# * Description: Spring Boot application configuration.
# */
spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${APP_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
